site:
  name: Elle & Alexander
  site: 'https://alexanderg.github.io'
  base: '/weddingSite'
  trailingSlash: false

  googleSiteVerificationId: ''

metadata:
  title:
    default: Elle & Alexander — August 28, 2026
    template: '%s — Elle & Alexander'
  description: 'Join us as we celebrate the marriage of Elle and Alexander on August 28, 2026 at TBD.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Elle & Alexander Wedding
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'

    list:
      isEnabled: true
      pathname: 'announcements'
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light:only'
